# coding=utf8
from selenium import webdriver
import time
from time import sleep
from selenium.webdriver.common.keys import Keys
import random
from selenium.common.exceptions import NoAlertPresentException
from selenium.common.exceptions import NoSuchElementException
import unittest

class longan(unittest.TestCase):
    def setUp(self):
        self.driver=webdriver.Chrome()
        self.driver.implicitly_wait(20)
        self.base_url='https://learn.longan.link/'
        self.verificationErrors= []
        self.accept_next_alert = True

    def test_1(self):
        driver = self.driver
        driver.get(self.base_url)
        driver.maximize_window()
        driver.find_element_by_partial_link_text('登录').click()
        driver.find_element_by_id('normal_login_username').send_keys('ABC')
        sleep(1)
        driver.find_element_by_id('normal_login_password').send_keys('123456', Keys.ENTER)
        driver.implicitly_wait(15)
        sleep(1)
        driver.find_element_by_partial_link_text('作品社区').click()
        a = driver.window_handles
        print("order page:", a)
        driver.switch_to.window(a[1])
        driver.find_element_by_xpath('//*[@id="frc-q-1088"]').send_keys('控制小会议室的灯', Keys.ENTER)
        sleep(5)
        driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div/div/div/a').click()
        driver.implicitly_wait(15)
        sleep(5)
        driver.find_element_by_xpath('//*[@class="green-flag_green-flag_1kiAo"]').click()
        sleep(15)
        driver.find_element_by_xpath('//*[@class="stop-all_stop-all_1Y8P9"]').click()
        driver.implicitly_wait(15)
        driver.back()
        driver.find_element_by_xpath('//*[@id="frc-q-1088"]').clear()
        sleep(3)
        driver.find_element_by_xpath('//*[@id="frc-q-1088"]').send_keys('像素鸟3', Keys.ENTER)
        sleep(5)
        driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div/div/div/a').click()
        driver.implicitly_wait(15)
        sleep(5)
        driver.find_element_by_xpath('//*[@class="green-flag_green-flag_1kiAo"]').click()
        sleep(6)
        driver.find_element_by_xpath('//*[@class="stop-all_stop-all_1Y8P9"]').click()
        driver.implicitly_wait(15)
        driver.back()
        driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[3]/a').click()
        driver.implicitly_wait(10)
        sleep(5)
        driver.find_element_by_xpath('//*[@id="projectBox"]/button/span').click()
        time.sleep(2)
        driver.find_element_by_xpath('//*[@id="projectBox"]/button/span').click()
        time.sleep(2)
        driver.find_element_by_xpath('//*[@id="projectBox"]/button/span').click()
        time.sleep(2)
        driver.find_element_by_xpath('//*[@id="projectBox"]/button/span').click()
        time.sleep(2)
        driver.find_element_by_xpath('//*[@id="projectBox"]/button/span').click()
        driver.implicitly_wait(5)
        sleep(3)
        driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div[1]/a/img').click()
        driver.implicitly_wait(15)
        sleep(5)
        driver.find_element_by_xpath(
            '//*[@id="view"]/div/div[1]/div[2]/div[1]/div/div[1]/div/div/div[1]/img[1]').click()
        sleep(10)
        driver.find_element_by_xpath(
            '//*[@id="view"]/div/div[1]/div[2]/div[1]/div/div[1]/div/div/div[1]/img[2]').click()
        sleep(3)
        driver.find_element_by_xpath('//*[@id="frc-compose-comment-3392903"]').send_keys(
            random.choice(['你好', '你好我好大家好', '祝你快乐每一天']))
        sleep(3)
        driver.find_element_by_xpath(
            '//*[@id="view"]/div/div[2]/div/div/div[1]/div[2]/div/div/form/div[2]/button[2]/span').click()
        sleep(3)
        driver.back()
        # driver.implicitly_wait(5)
        driver.find_element_by_xpath('//*[@id="view"]/div/div/div[2]/div/a[2]/li/img').click()
        # driver.implicitly_wait(15)
        driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div[2]/a').click()
        sleep(8)
        driver.back()
        driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[1]/a').click()
        driver.find_element_by_partial_link_text('创作平台').click()
        driver.implicitly_wait(10)
        b = driver.window_handles
        print("order page:", b)
        driver.switch_to.window(b[-1])
        driver.find_element_by_xpath('//*[@id="app"]/div/div[2]/div[1]/div[7]/span').click()
        sleep(4)
        driver.find_element_by_id('frc-title-1088').clear()
        sleep(3)
        driver.find_element_by_id('frc-title-1088').send_keys(random.choice(
            ['傾城之淚', '深知你是梦', '缥缈淡如风', '点燃暮色', '仙玉尘缘', '山间闲人', '大西瓜', '小南瓜', '海绵来啦', '妄念', '软妹贩卖机', '牛奶煮萝莉', '嘴角的樱桃汁',
             '难以再遇你','被风吹过灼思', '半颗心的暖']))
        sleep(1)
        driver.find_element_by_id('frc-instructions-3392903').send_keys('春晓 [唐]孟浩然')
        sleep(1)
        driver.find_element_by_id('frc-description-3392903').send_keys('春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。')
        sleep(1)
        driver.find_element_by_xpath('//*[@class="button action-button studio-button"]').click()
        sleep(3)
        driver.find_element_by_xpath('//*[@class="ant-tree-iconEle ant-tree-icon__customize"]').click()
        # driver.find_element_by_xpath('//*[@class="ant-tree-title"]').click()
        driver.implicitly_wait(3)
        sleep(2)
        driver.find_element_by_xpath('//*[@class="button action-button submit-button"]').click()
        driver.implicitly_wait(4)
        sleep(4)
        driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[6]/div/a/span').click()
        sleep(3)
        driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[6]/div/ul/li[1]/a/span').click()
        driver.implicitly_wait(4)
        driver.find_element_by_xpath('//*[@id="accountHome"]/section[2]/div[1]/div[1]/div[1]/a').click()
        sleep(2)
        # 撤回公开
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[5]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[6]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[7]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[8]/td[4]/div/button[1]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(2)
        # driver.find_element_by_xpath('//*[@class="anticon anticon-right"]').click()  # 点击切换下一页
        # sleep(3)
        driver.find_element_by_xpath(
            '//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[1]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # 删除作品
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.refresh()
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.refresh()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.refresh()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
        # sleep(1)
        driver.refresh()
        sleep(8)
        driver.quit()

    # 个人中心\我的管理
    def test_2(self):
        driver = self.driver
        driver.implicitly_wait(20)
        driver.get(self.base_url)
        driver.maximize_window()
        driver.find_element_by_partial_link_text('登录').click()
        driver.find_element_by_id('normal_login_username').send_keys('ABC')
        sleep(1)
        driver.find_element_by_id('normal_login_password').send_keys('123456', Keys.ENTER)
        driver.implicitly_wait(15)
        sleep(5)
        driver.find_element_by_xpath('//*[@id="header"]/div[2]/span').click()
        sleep(1)
        driver.find_element_by_partial_link_text('个人中心').click()
        sleep(5)
        driver.find_element_by_xpath('//*[@id="accountHome"]/section[1]/div[1]/a/img').click()
        sleep(1)
        driver.find_element_by_id('userform_description').clear()
        sleep(2)
        driver.find_element_by_id('userform_description').send_keys(random.choice(["这个人太懒了，什么都不写","这个人太懒了，什么都没写","这个人太懒了，什么都不想写",
                                                                                   "这个人太懒了，什么都不会写"]))
        sleep(3)
        driver.find_element_by_xpath('//*[@class="ant-btn submit ant-btn-primary"]').click()
        sleep(1)
        driver.back()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="accountHome"]/section[2]/div[1]/div[1]/div[1]/a').click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="manage"]/div[1]/div/ul/li[4]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/a/span').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[1]/div[2]/div[2]/div[1]/div[2]/a/button').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@class="ant-pagination-next"]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@class="ant-pagination-next"]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@class="ant-pagination-next"]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@class="ant-pagination-next"]').click()
        sleep(1)
        driver.back()
        driver.back()
        sleep(3)
        driver.find_element_by_xpath('//*[@id="manage"]/div[1]/div/ul/li[6]').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/span').click()
        sleep(1)
        driver.back()
        # driver.find_element_by_xpath('//*[@id="accountHome"]/section[2]/div[2]/div[1]/div[1]/a').click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="team"]/div[1]/div[1]/div[2]/span/input').send_keys('HHJ',Keys.ENTER)
        sleep(2)
        driver.back()
        driver.back()
        # driver.back()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="manage"]/div[1]/div/ul/li[2]').click()
        sleep(1)
        text=driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/a/span').click()
        if text == "撤回成功":
            print("通过")
        else:
            print("不通过")
        sleep(8)
        driver.quit()

    # 我要反馈
    def test_3(self):
        driver = self.driver
        driver.implicitly_wait(20)
        driver.get(self.base_url)
        driver.maximize_window()
        driver.find_element_by_partial_link_text('登录').click()
        driver.find_element_by_id('normal_login_username').send_keys('ABC')
        sleep(1)
        driver.find_element_by_id('normal_login_password').send_keys('123456', Keys.ENTER)
        driver.implicitly_wait(15)
        sleep(5)
        driver.find_element_by_xpath('//*[@id="header"]/div[2]/span').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="header"]/div[3]/div/div/ul/li[4]/span').click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="subject"]').send_keys('月很圆，花更香，保重身体要健康;鱼在游，鸟在叫，愿你天天哈哈笑;手中书，杯中酒，祝你好运天天有!欢乐多，忧愁少.')
        sleep(1)
        driver.find_element_by_xpath('//*[@id="content"]').send_keys('1.我们生活在同一个bai温暖的水域，也许偶尔会被水草缠绕，du但因为彼此温暖的呼zhi吸'
                                                                     '，相信都不会是死结。如果我说dao我爱你，我一直都爱你，不知道你会不会相信？——《双鱼记》'
                                                                     '2.爱是一场战争,我不怕受伤只怕你不快乐.——《离爱一个ID的距离》'
                                                                     '3.是别过头去,你就感觉不到我的深情?——《离爱一个ID的距离》'
                                                                     '4.爱情是一场注定的潮水，而自己就是一叶随时等待靠岸的小舟。潮来潮去，随波逐流，载沉载浮，在劫难逃。——《离爱一个ID的距离》'
                                                                     '5.在爱情这场戏里总是有一个主角和一个配角，——《爱在仙境的日子》'
                                                                     '6.像流水一样。金钱，地位，美丽，还有爱情，最后都会像流水一样。——《爱在仙境的日子》'
                                                                     '7.我一路狂奔，渴望在拥挤匆忙的人群里找到一个和我相似的面孔，她和我有相似的命运。我可以在她的身上看到自己命运的参照，何去何从，不再那么仓皇。'
                                                                     '——《小妖的金色城堡》'
                                                                     '8.她不会消失。消失的，不过是时间。而消失的时间，会让曾经的伤口，开出洁白而盛大的花朵，站成最纯洁的姿势，成为我们彼此温暖过存在过的最好证明。——《小妖的金色城堡》'
                                                                     '9.有点寂寞，有点痛，有点张扬，有点不知所措，有点需要安慰。那么，点开它，有点美。'
                                                                     '——《小妖的金色城堡》'
                                                                     '10.我在刀尖上舞蹈，沉重也好，轻盈也罢，从脚底到心里，终究是蔓延的疼痛－－《小妖的金色城堡》'
                                                                     '11.我没有月亮。这个月亮是很多人的，但不是我的。温暖遥不可及。——《校服的裙摆》')
        # sleep(2)
        # driver.find_element_by_xpath('//*[@id="root"]/section/header/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
        #         # sleep(3)
        #         # driver.find_element_by_xpath('//*[@id="header"]/div[2]/span').click()
        #         # sleep(1)
        #         # driver.find_element_by_xpath('//*[@id="header"]/div[3]/div/div/ul/li[4]/span').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="feedback_type"]/label[2]/span[2]').click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="subject"]').send_keys('月很圆，花更香，保重身体要健康;鱼在游，鸟在叫，愿你天天哈哈笑;手中书，杯中酒，祝你好运天天有!欢乐多，忧愁少.')
        sleep(1)
        driver.find_element_by_xpath('//*[@id="content"]').send_keys('1.我们生活在同一个bai温暖的水域，也许偶尔会被水草缠绕，du但因为彼此温暖的呼zhi吸'
                                                                     '，相信都不会是死结。如果我说dao我爱你，我一直都爱你，不知道你会不会相信？——《双鱼记》'
                                                                     '2.爱是一场战争,我不怕受伤只怕你不快乐.——《离爱一个ID的距离》'
                                                                     '3.是别过头去,你就感觉不到我的深情?——《离爱一个ID的距离》'
                                                                     '4.爱情是一场注定的潮水，而自己就是一叶随时等待靠岸的小舟。潮来潮去，随波逐流，载沉载浮，在劫难逃。——《离爱一个ID的距离》'
                                                                     '5.在爱情这场戏里总是有一个主角和一个配角，——《爱在仙境的日子》'
                                                                     '6.像流水一样。金钱，地位，美丽，还有爱情，最后都会像流水一样。——《爱在仙境的日子》'
                                                                     '7.我一路狂奔，渴望在拥挤匆忙的人群里找到一个和我相似的面孔，她和我有相似的命运。我可以在她的身上看到自己命运的参照，何去何从，不再那么仓皇。'
                                                                     '——《小妖的金色城堡》'
                                                                     '8.她不会消失。消失的，不过是时间。而消失的时间，会让曾经的伤口，开出洁白而盛大的花朵，站成最纯洁的姿势，成为我们彼此温暖过存在过的最好证明。——《小妖的金色城堡》'
                                                                     '9.有点寂寞，有点痛，有点张扬，有点不知所措，有点需要安慰。那么，点开它，有点美。'
                                                                     '——《小妖的金色城堡》'
                                                                     '10.我在刀尖上舞蹈，沉重也好，轻盈也罢，从脚底到心里，终究是蔓延的疼痛－－《小妖的金色城堡》'
                                                                     '11.我没有月亮。这个月亮是很多人的，但不是我的。温暖遥不可及。——《校服的裙摆》')
        # sleep(2)
        # driver.find_element_by_xpath('//*[@id="root"]/section/header/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
        # sleep(3)
        # driver.find_element_by_xpath('//*[@id="header"]/div[2]/span').click()
        # sleep(1)
        # driver.find_element_by_xpath('//*[@id="header"]/div[3]/div/div/ul/li[4]/span').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="feedback_type"]/label[3]/span[2]').click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="subject"]').send_keys('月很圆，花更香，保重身体要健康;鱼在游，鸟在叫，愿你天天哈哈笑;手中书，杯中酒，祝你好运天天有!欢乐多，忧愁少.')
        sleep(1)
        driver.find_element_by_xpath('//*[@id="content"]').send_keys('1.我们生活在同一个bai温暖的水域，也许偶尔会被水草缠绕，du但因为彼此温暖的呼zhi吸'
                                                                     '，相信都不会是死结。如果我说dao我爱你，我一直都爱你，不知道你会不会相信？——《双鱼记》'
                                                                     '2.爱是一场战争,我不怕受伤只怕你不快乐.——《离爱一个ID的距离》'
                                                                     '3.是别过头去,你就感觉不到我的深情?——《离爱一个ID的距离》'
                                                                     '4.爱情是一场注定的潮水，而自己就是一叶随时等待靠岸的小舟。潮来潮去，随波逐流，载沉载浮，在劫难逃。——《离爱一个ID的距离》'
                                                                     '5.在爱情这场戏里总是有一个主角和一个配角，——《爱在仙境的日子》'
                                                                     '6.像流水一样。金钱，地位，美丽，还有爱情，最后都会像流水一样。——《爱在仙境的日子》'
                                                                     '7.我一路狂奔，渴望在拥挤匆忙的人群里找到一个和我相似的面孔，她和我有相似的命运。我可以在她的身上看到自己命运的参照，何去何从，不再那么仓皇。'
                                                                     '——《小妖的金色城堡》'
                                                                     '8.她不会消失。消失的，不过是时间。而消失的时间，会让曾经的伤口，开出洁白而盛大的花朵，站成最纯洁的姿势，成为我们彼此温暖过存在过的最好证明。——《小妖的金色城堡》'
                                                                     '9.有点寂寞，有点痛，有点张扬，有点不知所措，有点需要安慰。那么，点开它，有点美。'
                                                                     '——《小妖的金色城堡》'
                                                                     '10.我在刀尖上舞蹈，沉重也好，轻盈也罢，从脚底到心里，终究是蔓延的疼痛－－《小妖的金色城堡》'
                                                                     '11.我没有月亮。这个月亮是很多人的，但不是我的。温暖遥不可及。——《校服的裙摆》')
        # sleep(2)
        text=driver.find_element_by_xpath('//*[@id="root"]/section/header/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
        if text == "提交成功，感谢你的反馈":
            print("通过")
        else:
            print("不通过")
        # sleep(1)
        # driver.refresh()
        sleep(3)
        driver.quit()

    # 注册、登录
    def test_4(self):
        driver = self.driver
        driver.implicitly_wait(20)
        driver.get(self.base_url)
        driver.maximize_window()
        driver.find_element_by_partial_link_text('注册').click()
        sleep(1)
        driver.find_element_by_id('normal_login_username').send_keys('ddb')
        sleep(1)
        driver.find_element_by_id('normal_login_password').send_keys('123456')
        sleep(1)
        driver.find_element_by_xpath('//*[@id="normal_login_repectpassword"]').send_keys('123456')
        sleep(1)
        driver.find_element_by_id('normal_login_phone').send_keys('13512345612')
        sleep(1)
        driver.find_element_by_id('normal_login_agreement').click()
        sleep(1)
        driver.find_element_by_xpath('//*[@id="normal_login"]/div[5]/div/div/div/button').click()
        sleep(1)
        driver.find_element_by_id('normal_login_captcha').send_keys('132465')
        sleep(1)
        driver.find_element_by_xpath('//*[@id="normal_login"]/button').click()
        sleep(5)
        driver.find_element_by_xpath('//*[@id="normal_login"]/div[7]/div/div/div/a/button').click()
        sleep(1)
        driver.find_element_by_id('normal_login_username').send_keys('ABC')
        sleep(1)
        driver.find_element_by_id('normal_login_password').send_keys('123456')
        sleep(1)
        text=driver.find_element_by_xpath('//*[@id="normal_login"]/div[4]/div/div/div/button').click()
        if text == "登陆失败":
            print("不通过")
        else:
            print("通过")
        sleep(3)
        driver.quit()


    def is_element_present(self, how, what):
        try:
            self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e:
            return False
        return True