# coding=utf8

from selenium import webdriver
from time import sleep
from selenium.webdriver.common.keys import Keys
# from pymouse import PyMouse
driver=webdriver.Chrome()
url='https://longan.link/'
driver.get(url)
driver.maximize_window()
driver.find_element_by_xpath('//*[@class="advantageTitle_2Pf9"]').click()
driver.implicitly_wait(3)
a=driver.window_handles
print("order page:", a)
driver.switch_to.window(a[0])
driver.find_element_by_partial_link_text('我是教育工作者').click()
driver.implicitly_wait(3)
b=driver.window_handles
print("order page:", b)
driver.switch_to.window(b[0])
driver.find_element_by_partial_link_text('关于龙眼').click()
driver.implicitly_wait(2)
c=driver.window_handles
print("order page:", c)
driver.switch_to.window(c[0])
driver.find_element_by_partial_link_text('技术文档').click()
driver.implicitly_wait(2)
d=driver.window_handles
print("order page:", d)
driver.switch_to.window(d[0])
driver.find_element_by_partial_link_text('魔法视频').click()
driver.implicitly_wait(2)
e=driver.window_handles
print("order page:", e)
driver.switch_to.window(e[0])
driver.find_element_by_partial_link_text('支持组件').click()
driver.implicitly_wait(2)
f=driver.window_handles
print("order page:", f)
driver.switch_to.window(f[0])
driver.find_element_by_partial_link_text('校内方案').click()
driver.implicitly_wait(2)
sleep(2)
driver.find_element_by_partial_link_text('校外方案').click()
driver.implicitly_wait(2)
sleep(2)
driver.find_element_by_partial_link_text('学习中心').click()
driver.implicitly_wait(2)
g=driver.window_handles
print("order page:", g)
driver.switch_to.window(g[0])
driver.find_element_by_partial_link_text('资讯').click()
driver.implicitly_wait(2)
sleep(2)
driver.find_element_by_xpath('//*[@class="navbar__logo"]').click()
sleep(3)
aa=driver.window_handles
print("order page:", aa)
driver.switch_to.window(aa[1])
driver.find_element_by_partial_link_text('登录').click()
driver.implicitly_wait(3)
sleep(3)
driver.find_element_by_id('normal_login_username').send_keys('ABC')
driver.implicitly_wait(2)
sleep(3)
driver.find_element_by_id('normal_login_password').send_keys('123456',Keys.ENTER)
driver.implicitly_wait(2)
sleep(3)
driver.find_element_by_xpath('//*[@class="user ant-dropdown-trigger"]').click()
driver.implicitly_wait(3)
sleep(3)
driver.find_element_by_partial_link_text('教学课程').click()
driver.implicitly_wait(3)
sleep(3)
driver.find_element_by_partial_link_text('探索项目').click()
driver.implicitly_wait(2)
sleep(3)
driver.find_element_by_partial_link_text('虚拟宠物').click()
driver.implicitly_wait(10)
driver.find_element_by_xpath('//*[@class="dplayer-video dplayer-video-current"]').click()
sleep(60)
# driver.find_element_by_partial_link_text('找到拉里').click()
# driver.implicitly_wait(10)
# driver.find_element_by_xpath('//*[@class="dplayer-icon dplayer-play-icon"]').click()
# sleep(60)
driver.find_element_by_partial_link_text('探索项目').click()
driver.implicitly_wait(2)
sleep(13)

# driver.quit()
# driver.close()
