#coding=utf8
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.keys import Keys
import random
import sys
from HTMLTestRunnerCN import HTMLTestRunner
import os
sys.path.append(os.getcwd())
driver=webdriver.Chrome()
url='https://learn.longan.link/'
driver.get(url)
driver.maximize_window()
driver.implicitly_wait(15)
driver.find_element_by_partial_link_text('登录').click()
# driver.implicitly_wait(5)
driver.find_element_by_id('normal_login_username').send_keys('ABC')
sleep(1)
driver.find_element_by_id('normal_login_password').send_keys('123456')
driver.implicitly_wait(15)
sleep(1)
driver.find_element_by_partial_link_text('作品社区').click()
a=driver.window_handles
print("order page:", a)
driver.switch_to.window(a[1])
driver.find_element_by_xpath('//*[@id="frc-q-1088"]').send_keys('控制小会议室的灯',Keys.ENTER)
sleep(5)
driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div/div/div/a').click()
driver.implicitly_wait(15)
sleep(5)
driver.find_element_by_xpath('//*[@class="green-flag_green-flag_1kiAo"]').click()
sleep(15)
driver.find_element_by_xpath('//*[@class="stop-all_stop-all_1Y8P9"]').click()
driver.implicitly_wait(15)
driver.back()
driver.find_element_by_xpath('//*[@id="frc-q-1088"]').clear()
sleep(3)
driver.find_element_by_xpath('//*[@id="frc-q-1088"]').send_keys('像素鸟3',Keys.ENTER)
sleep(5)
driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div/div/div/a').click()
driver.implicitly_wait(15)
sleep(5)
driver.find_element_by_xpath('//*[@class="green-flag_green-flag_1kiAo"]').click()
sleep(6)
driver.find_element_by_xpath('//*[@class="stop-all_stop-all_1Y8P9"]').click()
driver.implicitly_wait(15)
driver.back()
driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[3]/a').click()
driver.implicitly_wait(10)
sleep(5)
driver.find_element_by_partial_link_text('跳舞的芭蕾女孩').click()
driver.implicitly_wait(15)
sleep(10)
driver.find_element_by_xpath('//*[@id="view"]/div/div[1]/div[2]/div[1]/div/div[1]/div/div/div[1]/img[1]').click()
sleep(10)
driver.find_element_by_xpath('//*[@id="view"]/div/div[1]/div[2]/div[1]/div/div[1]/div/div/div[1]/img[2]').click()
sleep(5)
driver.find_element_by_xpath('//*[@id="frc-compose-comment-3392903"]').send_keys(random.choice(['月很圆，花更香，保重身体要健康;鱼在游，鸟在叫，愿你天天哈哈笑;手中书，杯中酒，祝你好运天天有!欢乐多，忧愁少.','你好我好大家好','祝你快乐每一天']))
sleep(5)
driver.find_element_by_xpath('//*[@id="view"]/div/div[2]/div/div/div[1]/div[2]/div/div/form/div[2]/button[2]/span').click()
sleep(6)
driver.back()
# driver.implicitly_wait(5)
driver.find_element_by_xpath('//*[@id="view"]/div/div/div[2]/div/a[2]/li/img').click()
# driver.implicitly_wait(15)
driver.find_element_by_xpath('//*[@id="projectBox"]/div/div/div[2]/a').click()
sleep(8)
driver.back()
driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[1]/a').click()
driver.find_element_by_partial_link_text('创作平台').click()
driver.implicitly_wait(10)
b=driver.window_handles
print("order page:", b)
driver.switch_to.window(b[-1])
driver.find_element_by_xpath('//*[@id="app"]/div/div[2]/div[1]/div[7]/span').click()
sleep(4)
driver.find_element_by_id('frc-title-1088').clear()
sleep(3)
driver.find_element_by_id('frc-title-1088').send_keys(random.choice(['傾城之淚', '深知你是梦', '缥缈淡如风','点燃暮色','仙玉尘缘','山间闲人','大西瓜','小南瓜','海绵来啦','妄念','软妹贩卖机','牛奶煮萝莉','嘴角的樱桃汁','难以再遇你',
                                                                     '被风吹过灼思','半颗心的暖']))
sleep(1)
driver.find_element_by_id('frc-instructions-3392903').send_keys(["春晓[唐] 孟浩然"])
sleep(1)
driver.find_element_by_id('frc-description-3392903').send_keys('春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。')
sleep(1)
driver.find_element_by_xpath('//*[@class="button action-button studio-button"]').click()
sleep(3)
driver.find_element_by_xpath('//*[@class="ant-tree-iconEle ant-tree-icon__customize"]').click()
# driver.find_element_by_xpath('//*[@class="ant-tree-title"]').click()
driver.implicitly_wait(3)
sleep(2)
driver.find_element_by_xpath('//*[@class="button action-button submit-button"]').click()
driver.implicitly_wait(4)
sleep(4)
driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[6]/div/a/span').click()
sleep(3)
driver.find_element_by_xpath('//*[@id="navigation"]/div/ul/li[6]/div/ul/li[1]/a/span').click()
driver.implicitly_wait(4)
driver.find_element_by_xpath('//*[@id="accountHome"]/section[2]/div[1]/div[1]/div[1]/a').click()
sleep(2)
#撤回公开
driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[1]').click()
sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[5]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[6]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[7]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[8]/td[4]/div/button[1]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(2)
# driver.find_element_by_xpath('//*[@class="anticon anticon-right"]').click()  # 点击切换下一页
# sleep(3)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[1]').click()
# sleep(1)
driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# 删除作品
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.refresh()
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.refresh()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.refresh()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[4]/div/button[2]').click()
# sleep(1)
# driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
# sleep(1)
# driver.find_elements_by_class_name('common_button')[0].click()
text=driver.find_element_by_xpath('//*[@id="manageProject"]/div[2]/div[2]/div/div[2]/div/div[2]/button[2]').click()
if text == "撤回作品成功":
    print("通过")
else:
    print("不通过")

# driver.refresh()
sleep(3)
driver.quit()
print(sys.path)